### ISSUE TITLE
New Plugin?(got told to put it here)((closed))

### ISSUE THREAD

**Issue by iBleedForMyDonut** [CAC27/EnhancedDiscord#10]
a plugin made for ED, when you hold DELETE and click a message, it deletes, its the only thing Im missing in ED

Github link: https://github.com/Inve1951/BetterDiscordStuff/blob/master/plugins/QuickDeleteMessages.plugin.js

**Comment by Thatlifeofgames** [comment]
Already been posted here https://github.com/CAC27/EnhancedDiscord/issues/8

**Comment by PhillipAB** [comment]
Get good

**Comment by iBleedForMyDonut** [comment]
Oh, sorry didn't see it

**Comment by Thatlifeofgames** [comment]
You know you can close issues properly

**Comment by iBleedForMyDonut** [comment]
ya ive never used github
