### ISSUE TITLE
Default theme f*cking up

### ISSUE THREAD

**Issue by xenorio** [CAC27/EnhancedDiscord#58]
Lower left corner of Discord: [https://imgur.com/a/NFL9ALq](https://imgur.com/a/NFL9ALq)

pls fix

**Comment by IndyV** [comment]
This doesn't seem related to ED itself.
Please go to the [Discord-Theme](https://github.com/joe27g/Discord-Theme) repository.

**Comment by Xenorio** [comment]
@IndyV oh, sorry. didn't know that existet. i just thought since it's the default theme i'd post it here.
