### ISSUE TITLE
EnhancedDiscord freezes when loading large user lists

### ISSUE THREAD

**Issue by Thatlifeofgames** [CAC27/EnhancedDiscord#7]
When loading a large user list, discord freezes for a while until its loaded. 

Go somewhere like discord bots or discord bot list to see what I mean. It happens to lots of people.

**Comment by CAC27** [comment]
Seems to be an issue with the theme itself; Doesn't happen when deleting `style.css`. Might have to experiment with using URLs to themes instead.

**Comment by CAC27** [comment]
Looks like it's fixed in 1a174e2. I'll reopen this if anyone still has problems.
