### ISSUE TITLE
Easier message editing/deleting

### ISSUE THREAD

**Issue by Thatlifeofgames** [CAC27/EnhancedDiscord#8]
Double-clicking to edit a message could be quite useful, it has been done in BD.
Also holding delete while clicking a message might be easier too. (Jakuski's idea)

**Comment by Rhyss-me** [comment]
something like this plugin for better discord then.. http://Jay.is-fi.re/5b8df3.js

**Comment by Thatlifeofgames** [comment]
I did actually say in the OP that it's been done in BD..

**Comment by Rhyss-me** [comment]
im blind sorry lmao

**Comment by CAC27** [comment]
Done as of 3a38b4a :)
